name: Makefile CI

on:
  push:
    branches: [ "cooperative-a" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Compile program
      run: make

    - name: Compile tester
      run: make test

    - name: Run tester
      run: chmod 777 ./test
      run: ./test
